class CapsuleSort:

    BOOKING_MSG = "BOOKING_MSG"
    UPDATE_MSG = "UPDATE_MSG"
    INFORMATION_DEVICE_MSG = "INFORMATION_DEVICE_MSG"
    LDAP_ADD_MSG = "LDAP_ADD_MSG"
    LDAP_DEL_MSG = "LDAP_DEL_MSG"
    LDAP_MOD_MSG = "LDAP_MOD_MSG"